title: Sanchit Khope
description: Portfolio for TEJ20R
author:
  name: Sanchit Khope
  email: khopesanchit25@gmail.com
url: "https://sanchitportfolio.github.io"
baseurl: "" # Set to "/repository-name" for project sites
